version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '${PORT_DB}:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    #networks:
    #  - backend
  #api:
  #  build: ./backend-example
  #  ports:
  #    - "3000:3000"
  #  expose:
  #    - "3000"
  #  depends_on:
  #    - db
  #  env_file:
  #    - .env
  #  environment:
  #    - VARIABLEDEENTORNO=valorss
  #    - VARIABLEDEENTORNO_2=${PORT_DB}
  #dashboard:
    #build: ./front-example
    #depends_on:
    #  - api
    #ports:
    #  - "4200:4200"
    #expose:
    #  - "4200"
    #networks:
    #  - backend
#networks:
 # - backend:
volumes:
  db:
    driver: local
